os: linux
dist: focal
language: shell

services:
  - docker

env:
  DOCKER_USERNAME: sineverba
  DOCKER_IMAGE: php8xc

before_install:
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      docker -v | grep "19.03" || travis_terminate 1;
      mkdir -vp ~/.docker/cli-plugins/ || travis_terminate 1;
      curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx || travis_terminate 1;
      chmod a+x ~/.docker/cli-plugins/docker-buildx || travis_terminate 1;
      docker buildx version || travis_terminate 1;
    fi

install:
  - |
    if [[ $TRAVIS_TAG == "" ]]; then
      echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1;
      docker build --tag $DOCKER_USERNAME/$DOCKER_IMAGE . || travis_terminate 1;
    fi

script:
  - |
    if [[ $TRAVIS_TAG == "" ]]; then
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -v | grep 8.0.1 || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -v | grep OPcache || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -m | grep xdebug || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -r "xdebug_info();" | grep "3.0.2" || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -m | grep pdo_pgsql || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE /usr/bin/composer -V | grep "2.0.9" || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -i | grep "short_open_tag => Off => Off" || travis_terminate 1;
      docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE php -i | grep "memory_limit => 512M => 512M" || travis_terminate 1;
    fi
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      echo "Start build and push";
    fi

after_success:
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1;
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes || travis_terminate 1;
      docker buildx create --name mybuilder && docker buildx use mybuilder && docker buildx inspect --bootstrap || travis_terminate 1;
      docker buildx build \
        --platform linux/amd64,linux/arm/v6,linux/arm/v7 \
        --tag $DOCKER_USERNAME/$DOCKER_IMAGE:$TRAVIS_TAG \
        --tag $DOCKER_USERNAME/$DOCKER_IMAGE:latest \
        --push . || travis_terminate 1;
    fi